<?php

$this->pageBreadcrumbs()->setItems([
    'Customers' => $this->url('home'),
]);
?>



<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>                  
        </div>

        <?= $this->formElement($form->get('create')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

