<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
    'Customer' => $this->url('home')
]);
?>
<a href="<?= $this->url('application',['action'=>'add-customer'])?>" class="btn">Add Customer</a>
<table id="example" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach ($data as $val) { ?>
        <tr>
            <td><?= $val->getName()?></td>
            <td><?= $val->getDescription()?></td>
            <td><?= $val->getCreatedAt()->format('Y-m-d H:i:s')?></td>
            <td>
                <a href="<?= $this->url('application',['action'=>'edit-customer', 'id'=>$val->getId()])?>">Edit </a>
                | <a href="<?= $this->url('application',['action'=>'transaction', 'id'=>$val->getId()])?>">Transaction </a>
            </td>

        </tr>
        <?php } ?>

    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>